name: PHP Fix
on:
  pull_request:
    types:
      - labeled
      - unlabeled
      - synchronize

jobs:
  run:
    runs-on: ubuntu-latest
    name: Fixing...
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          tools: composer:v2

      - name: Get composer cache directory
        id: composercache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"
        working-directory: ./backend

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composercache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install dependencies
        run: composer install --prefer-dist --no-interaction --no-progress
        working-directory: ./backend

      - name: Execute insights
        run:  php artisan insights --fix -n --ansi
        working-directory: ./backend

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Apply php-cs-fixer changes
          commit_author: Aios <aioslike@gmail.com>


      - name: Remove fix labels
        uses: andymckay/labeler@master
        with:
          remove-labels: "php:fix"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}




